AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

Lint/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: keyword

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/MultilineBlockChain:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/AndOr:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails
